import type { ItemDraft } from "./types";

/**
 * A small demo closet so the app can be explored before any real photos are
 * added. Wear history is expressed as "days ago" so the sample always looks
 * freshly lived-in. Sample pieces carry no photos — the category glyph stands
 * in, which is exactly what a real un-photographed piece looks like.
 */
export interface SampleSpec extends ItemDraft {
  wearsAgo: number[];
  /** Basename under /public/sample, fetched and stored like an uploaded photo. */
  art?: string;
}

export const SAMPLE_CLOSET: SampleSpec[] = [
  {
    name: "Ivory silk blouse",
    category: "tops",
    subtype: "Wrap blouse",
    brand: "Everlane",
    color: "cream",
    size: "S",
    seasons: ["spring", "fall"],
    formality: "work",
    tags: ["office", "layering"],
    price: 98,
    favorite: true,
    art: "silk-blouse",
    wearsAgo: [2, 11, 23, 40],
  },
  {
    name: "Black wide-leg trousers",
    category: "bottoms",
    brand: "COS",
    color: "black",
    size: "M",
    seasons: ["fall", "winter", "spring"],
    formality: "work",
    tags: ["office", "everyday"],
    price: 135,
    art: "wide-leg-trousers",
    wearsAgo: [1, 5, 9, 16, 28, 44],
  },
  {
    name: "Poppy midi dress",
    category: "dresses",
    subtype: "Tiered midi",
    brand: "Reformation",
    color: "red",
    seasons: ["summer"],
    formality: "party",
    tags: ["date night", "wedding guest", "statement"],
    price: 248,
    favorite: true,
    art: "midi-dress",
    wearsAgo: [64],
  },
  {
    name: "Camel wool coat",
    category: "outerwear",
    brand: "Sézane",
    color: "beige",
    size: "M",
    seasons: ["fall", "winter"],
    formality: "everyday",
    tags: ["layering", "dry clean"],
    price: 420,
    art: "wool-coat",
    wearsAgo: [128, 141],
  },
  {
    name: "Tan ankle boots",
    category: "shoes",
    brand: "Madewell",
    color: "brown",
    size: "8",
    seasons: ["fall", "winter"],
    formality: "everyday",
    tags: ["everyday"],
    price: 178,
    art: "ankle-boots",
    wearsAgo: [3, 8, 15, 31, 52],
  },
  {
    name: "Straw market tote",
    category: "bags",
    color: "cream",
    seasons: ["summer"],
    formality: "casual",
    tags: ["vacation", "weekend"],
    art: "market-tote",
    wearsAgo: [210],
  },
  {
    name: "Emerald slip skirt",
    category: "bottoms",
    subtype: "Bias-cut satin",
    color: "green",
    size: "S",
    seasons: ["spring", "summer"],
    formality: "party",
    tags: ["date night"],
    price: 88,
    art: "slip-skirt",
    wearsAgo: [],
  },
  {
    name: "Grandmother's pearl studs",
    category: "jewelry",
    color: "white",
    seasons: [],
    formality: "formal",
    tags: ["sentimental", "wedding guest"],
    favorite: true,
    art: "pearl-studs",
    wearsAgo: [64, 300],
  },
  {
    name: "Oatmeal cashmere cardigan",
    category: "tops",
    brand: "Quince",
    color: "beige",
    size: "M",
    seasons: ["fall", "winter"],
    formality: "casual",
    tags: ["cozy", "layering"],
    price: 120,
    art: "cashmere-cardigan",
    wearsAgo: [4, 12, 19, 26, 33, 47, 61],
  },
  {
    name: "Indigo straight jeans",
    category: "bottoms",
    brand: "Levi's",
    color: "denim",
    size: "27",
    seasons: ["spring", "fall", "winter"],
    formality: "casual",
    tags: ["weekend", "everyday"],
    price: 98,
    art: "straight-jeans",
    wearsAgo: [0, 6, 13, 20, 34],
  },
  {
    name: "Charcoal running leggings",
    category: "activewear",
    brand: "Lululemon",
    color: "grey",
    size: "S",
    seasons: ["spring", "summer", "fall", "winter"],
    formality: "casual",
    tags: ["everyday"],
    price: 128,
    art: "running-leggings",
    wearsAgo: [1, 3, 7, 10, 14, 21, 29],
  },
  {
    name: "Silk scarf, botanical print",
    category: "accessories",
    color: "print",
    seasons: ["spring", "summer"],
    formality: "everyday",
    tags: ["statement", "vintage"],
    art: "silk-scarf",
    wearsAgo: [188],
  },
];
